#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : persistent
Version  : 4.2.2
Release  : 1
URL      : https://pypi.python.org/packages/3d/71/3302512282b606ec4d054e09be24c065915518903b29380b6573bff79c24/persistent-4.2.2.tar.gz
Source0  : https://pypi.python.org/packages/3d/71/3302512282b606ec4d054e09be24c065915518903b29380b6573bff79c24/persistent-4.2.2.tar.gz
Summary  : Translucent persistent objects
Group    : Development/Tools
License  : ZPL-2.1
Requires: persistent-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zope.interface

%description
``persistent``:  automatic persistence for Python objects
=========================================================

%package dev
Summary: dev components for the persistent package.
Group: Development
Provides: persistent-devel

%description dev
dev components for the persistent package.


%package python
Summary: python components for the persistent package.
Group: Default

%description python
python components for the persistent package.


%prep
%setup -q -n persistent-4.2.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485889308
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1485889308
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/python2.7/persistent/cPersistence.h
/usr/include/python2.7/persistent/ring.h
/usr/include/python3.6m/persistent/cPersistence.h
/usr/include/python3.6m/persistent/ring.h

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
