#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : persistent
Version  : 4.4.3
Release  : 24
URL      : https://files.pythonhosted.org/packages/56/a3/b63bc36720b07c7f9c7f448d8fa338dc59633f606c6d4230a4a70f8c8d16/persistent-4.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/56/a3/b63bc36720b07c7f9c7f448d8fa338dc59633f606c6d4230a4a70f8c8d16/persistent-4.4.3.tar.gz
Summary  : Translucent persistent objects
Group    : Development/Tools
License  : ZPL-2.1
Requires: persistent-license = %{version}-%{release}
Requires: persistent-python = %{version}-%{release}
Requires: persistent-python3 = %{version}-%{release}
Requires: Sphinx
Requires: repoze.sphinx.autointerface
Requires: zope.interface
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zope.interface

%description
=========================================================

%package dev
Summary: dev components for the persistent package.
Group: Development
Provides: persistent-devel = %{version}-%{release}

%description dev
dev components for the persistent package.


%package license
Summary: license components for the persistent package.
Group: Default

%description license
license components for the persistent package.


%package python
Summary: python components for the persistent package.
Group: Default
Requires: persistent-python3 = %{version}-%{release}

%description python
python components for the persistent package.


%package python3
Summary: python3 components for the persistent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the persistent package.


%prep
%setup -q -n persistent-4.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540217292
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/persistent
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/persistent/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/python3.7m/persistent/cPersistence.h
/usr/include/python3.7m/persistent/ring.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/persistent/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
